# Generated by Django 5.2.5 on 2025-09-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('mail', models.EmailField(max_length=255, verbose_name='メール')),
                ('gender', models.BooleanField(verbose_name='性別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='削除日')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('uodated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='削除日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='api.member')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='api.tag')),
            ],
        ),
    ]
